-- MySQL Script generated by MySQL Workbench
-- Sun Dec  4 13:26:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bunglebuild
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bunglebuild
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bunglebuild` DEFAULT CHARACTER SET utf8 ;
USE `bunglebuild` ;

-- -----------------------------------------------------
-- Table `bunglebuild`.`tareas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bunglebuild`.`tareas` ;

CREATE TABLE IF NOT EXISTS `bunglebuild`.`tareas` (
  `idtarea` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `poblacion` VARCHAR(45) NOT NULL,
  `codpostal` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `fechacreacion` VARCHAR(45) NOT NULL,
  `idusuario` INT NOT NULL,
  `fechafin` VARCHAR(45) NULL,
  `anotaantes` VARCHAR(45) NULL,
  `anotapost` VARCHAR(45) NULL,
  PRIMARY KEY (`idtarea`))
ENGINE = InnoDB;

-- 
-- Volcar la base de datos para la tabla `tareas`
-- 

INSERT INTO `tareas` VALUES 
(1, '42804790X', 'Pepe', 'Gomez', '665478153', 'alicatado', 'pepe@gmail.com', 'Calle Falsa 123', 'Huelva', '21005', 'Huelva', 'P', '2022-12-04', 2, NULL, NULL, NULL),
(2, '45604731G', 'Clara', 'Perez', '785478112', 'cimentacion', 'clara@gmail.com', 'Calle Falsa 23', 'Niebla', '21055', 'Huelva', 'R', '2022-12-02', 3, '2022-12-08', NULL, NULL),
(3, '44604768B', 'Juan', 'Bueno', '614 781 650', 'pintura', 'juan@gmail.com', 'Calle Falsa 78', 'Moguer', '21482', 'Huelva', 'C', '2022-12-06', 3, '2022-12-07', NULL, 'El cliente cambio de idea');


-- -----------------------------------------------------
-- Table `bunglebuild`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bunglebuild`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `bunglebuild`.`usuarios` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;

-- 
-- Volcar la base de datos para la tabla `usuarios`
-- 

INSERT INTO `usuarios` VALUES (1, 'admin', 'admin', 'administrador'),
(2, 'Manolo', 'm1234', 'operario'),
(3, 'Ana', 'a1234', 'operario'),
(4, 'Antonio', 'a1234', 'operario');


-- -----------------------------------------------------
-- Table `bunglebuild`.`tbl_comunidadesautonomas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bunglebuild`.`tbl_comunidadesautonomas` ;

CREATE TABLE IF NOT EXISTS `bunglebuild`.`tbl_comunidadesautonomas` (
  `id` TINYINT(4) NOT NULL DEFAULT 0,
  `nombre` VARCHAR(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  INDEX `nombre` (`nombre` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Afiliados de alta';

-- 
-- Volcar la base de datos para la tabla `tbl_comunidadesautonomas`
-- 

INSERT INTO `tbl_comunidadesautonomas` VALUES (1, 'Andalucía'),
(2, 'Aragón'),
(3, 'Asturias (Principado de)'),
(4, 'Balears (IIles)'),
(5, 'Canarias'),
(6, 'Cantabria'),
(8, 'Castilla y León'),
(7, 'Castilla-La Mancha'),
(9, 'Cataluña'),
(18, 'Ceuta'),
(10, 'Comunidad Valenciana'),
(11, 'Extremadura'),
(12, 'Galicia'),
(13, 'Madrid (Comunidad de)'),
(19, 'Melilla'),
(14, 'Murcia (Región de)'),
(15, 'Navarra (Comunidad Foral de)'),
(16, 'País Vasco'),
(17, 'Rioja (La)');

-- -----------------------------------------------------
-- Table `bunglebuild`.`tbl_provincias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bunglebuild`.`tbl_provincias` ;

CREATE TABLE IF NOT EXISTS `bunglebuild`.`tbl_provincias` (
  `cod` CHAR(2) NOT NULL DEFAULT '00' COMMENT 'Código de la provincia de dos digitos',
  `nombre` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'Nombre de la provincia',
  `comunidad_id` TINYINT(4) NOT NULL COMMENT 'Código de la comunidad a la que pertenece',
  PRIMARY KEY (`cod`),
  INDEX `nombre` (`nombre` ASC),
  INDEX `FK_ComunidadAutonomaProv` (`comunidad_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Provincias de españa; 99 para seleccionar a Nacional';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- 
-- Volcar la base de datos para la tabla `tbl_provincias`
-- 

INSERT INTO `tbl_provincias` VALUES ('01', 'Alava', 16),
('02', 'Albacete', 7),
('03', 'Alicante', 10),
('04', 'Almera', 1),
('05', 'Avila', 8),
('06', 'Badajoz', 11),
('07', 'Balears (Illes)', 4),
('08', 'Barcelona', 9),
('09', 'Burgos', 8),
('10', 'Cáceres', 11),
('11', 'Cádiz', 1),
('12', 'Castellón', 10),
('13', 'Ciudad Real', 7),
('14', 'Córdoba', 1),
('15', 'Coruña (A)', 12),
('16', 'Cuenca', 7),
('17', 'Girona', 9),
('18', 'Granada', 1),
('19', 'Guadalajara', 7),
('20', 'Guipzcoa', 16),
('21', 'Huelva', 1),
('22', 'Huesca', 2),
('23', 'Jaén', 1),
('24', 'León', 8),
('25', 'Lleida', 9),
('26', 'Rioja (La)', 17),
('27', 'Lugo', 12),
('28', 'Madrid', 13),
('29', 'Málaga', 1),
('30', 'Murcia', 14),
('31', 'Navarra', 15),
('32', 'Ourense', 12),
('33', 'Asturias', 3),
('34', 'Palencia', 8),
('35', 'Palmas (Las)', 5),
('36', 'Pontevedra', 12),
('37', 'Salamanca', 8),
('38', 'Santa Cruz de Tenerife', 5),
('39', 'Cantabria', 6),
('40', 'Segovia', 8),
('41', 'Sevilla', 1),
('42', 'Soria', 8),
('43', 'Tarragona', 9),
('44', 'Teruel', 2),
('45', 'Toledo', 7),
('46', 'Valencia', 10),
('47', 'Valladolid', 8),
('48', 'Vizcaya', 16),
('49', 'Zamora', 8),
('50', 'Zaragoza', 2),
('51', 'Ceuta', 18),
('52', 'Melilla', 19);